# documentation https://pycrunch.com/docs/configuration-file
iscovery:
  exclusions:
  # (example) do not search tests in 'ignored_folder' folder
#  - ignored_folder/
  # do not search tests in 'test_ignored.py' file
#  - test_ignored.py
engine:
  runtime: django
env:
  # everything here will be passed as environment variables to the test runner
  DJANGO_SETTINGS_MODULE: backend.settings.dev
  DJANGO_ALLOW_ASYNC_UNSAFE: "true"